SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS SEC_USER;
DROP TABLE IF EXISTS SP_AGGREGATOR;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS USER_TYPE;




/* Create Tables */

CREATE TABLE ADDRESS
(
	ADDRESS_ID int NOT NULL AUTO_INCREMENT,
	LINE1 varchar(100) NOT NULL,
	LINE2 varchar(100) NOT NULL,
	CITY varchar(100) NOT NULL,
	STATE varchar(50) NOT NULL,
	ZIP varchar(7) NOT NULL,
	PRIMARY KEY (ADDRESS_ID),
	UNIQUE (ADDRESS_ID)
);


CREATE TABLE SEC_USER
(
	USER_ID int NOT NULL AUTO_INCREMENT,
	ENABLED binary,
	EXTERNAL_CODE varchar(255),
	FAILED_LOGIN_ATTEMPTS int,
	FAILED_PSSWD_RECOVERY_ATTEMPTS int,
	PASSWORD varchar(255) NOT NULL,
	SOFT_LOCK_EXPIRES time,
	TEMPORARY_PASSWORD binary,
	USERNAME varchar(255) NOT NULL,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) NOT NULL,
	EMAIL varchar(255) NOT NULL,
	ROLE_ID int NOT NULL,
	USER_TYPE_ID int NOT NULL,
	AGGREGATOR_ID int,
	PRIMARY KEY (USER_ID),
	UNIQUE (USER_ID),
	UNIQUE (ROLE_ID),
	UNIQUE (USER_TYPE_ID)
);


CREATE TABLE SP_AGGREGATOR
(
	AGGREGATOR_ID int NOT NULL AUTO_INCREMENT,
	BUSINESS_PHONE_NUM varchar(15),
	BUSINESS_PHONE_NUM_EXT varchar(10),
	BUSINESS_EMAIL_ADDRESS varchar(100),
	PHONE_NUM varchar(15),
	PHONE_NUM_EXT varchar(10),
	WEB_SITE_ADDRESS varchar(100),
	LOGO varchar(500),
	ADDRESS_ID int NOT NULL,
	PRIMARY KEY (AGGREGATOR_ID),
	UNIQUE (AGGREGATOR_ID),
	UNIQUE (ADDRESS_ID)
);


CREATE TABLE USER_ROLE
(
	ROLE_ID int NOT NULL AUTO_INCREMENT,
	INTERNAL_CODE varchar(255) NOT NULL,
	PRIMARY KEY (ROLE_ID),
	UNIQUE (ROLE_ID),
	UNIQUE (INTERNAL_CODE)
);


CREATE TABLE USER_TYPE
(
	USER_TYPE_ID int NOT NULL AUTO_INCREMENT,
	INTERNAL_CODE varchar(255) NOT NULL,
	PRIMARY KEY (USER_TYPE_ID),
	UNIQUE (USER_TYPE_ID),
	UNIQUE (INTERNAL_CODE)
);



/* Create Foreign Keys */

ALTER TABLE SP_AGGREGATOR
	ADD FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SEC_USER
	ADD FOREIGN KEY (AGGREGATOR_ID)
	REFERENCES SP_AGGREGATOR (AGGREGATOR_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SEC_USER
	ADD FOREIGN KEY (ROLE_ID)
	REFERENCES USER_ROLE (ROLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SEC_USER
	ADD FOREIGN KEY (USER_TYPE_ID)
	REFERENCES USER_TYPE (USER_TYPE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



