package com.impetus.process.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SpAggregator generated by hbm2java
 */
@Entity
@Table(name = "SP_AGGREGRATOR")
@GenericGenerator(name = "SpAggregator", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
		@Parameter(name = "segment_value", value = "SP_AGGREGRATOR"),
		@Parameter(name = "increment_size", value = "10"),
		@Parameter(name = "optimizer", value = "pooled") })
public class SpAggregator implements java.io.Serializable {

	/**
   * 
   */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(generator = "SpAggregator")
	@Column(name = "AGGREGATOR_ID")
	private Integer aggregatorId;
	private String businessPhoneNum;
	private String businessPhoneNumExt;
	private String businessEmailAddress;
	private String phoneNum;
	private String phoneNumExt;
	private String webSiteAddress;
	private String logo;
	private String template;
	private int addressId;

	public SpAggregator() {
	}

	public SpAggregator(Integer addressId) {
		this.addressId = addressId;
	}

	public SpAggregator(String businessPhoneNum, String businessPhoneNumExt,
			String businessEmailAddress, String phoneNum, String phoneNumExt,
			String webSiteAddress, String logo, int addressId, String template) {
		this.businessPhoneNum = businessPhoneNum;
		this.businessPhoneNumExt = businessPhoneNumExt;
		this.businessEmailAddress = businessEmailAddress;
		this.phoneNum = phoneNum;
		this.phoneNumExt = phoneNumExt;
		this.webSiteAddress = webSiteAddress;
		this.logo = logo;
		this.addressId = addressId;
		this.template = template;
	}

	public Integer getAggregatorId() {
		return this.aggregatorId;
	}

	public void setAggregatorId(int aggregatorId) {
		this.aggregatorId = aggregatorId;
	}

	@Column(name = "BUSINESS_PHONE_NUM", length = 15)
	public String getBusinessPhoneNum() {
		return this.businessPhoneNum;
	}

	public void setBusinessPhoneNum(String businessPhoneNum) {
		this.businessPhoneNum = businessPhoneNum;
	}

	@Column(name = "BUSINESS_PHONE_NUM_EXT", length = 10)
	public String getBusinessPhoneNumExt() {
		return this.businessPhoneNumExt;
	}

	public void setBusinessPhoneNumExt(String businessPhoneNumExt) {
		this.businessPhoneNumExt = businessPhoneNumExt;
	}

	@Column(name = "BUSINESS_EMAIL_ADDRESS", length = 100)
	public String getBusinessEmailAddress() {
		return this.businessEmailAddress;
	}

	public void setBusinessEmailAddress(String businessEmailAddress) {
		this.businessEmailAddress = businessEmailAddress;
	}

	@Column(name = "PHONE_NUM", length = 15)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	@Column(name = "PHONE_NUM_EXT", length = 10)
	public String getPhoneNumExt() {
		return this.phoneNumExt;
	}

	public void setPhoneNumExt(String phoneNumExt) {
		this.phoneNumExt = phoneNumExt;
	}

	@Column(name = "WEB_SITE_ADDRESS", length = 100)
	public String getWebSiteAddress() {
		return this.webSiteAddress;
	}

	public void setWebSiteAddress(String webSiteAddress) {
		this.webSiteAddress = webSiteAddress;
	}

	@Column(name = "LOGO", length = 500)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "ADDRESS_ID", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}
	
	@Column(name = "template")
  public String getTemplate()
  {
    return template;
  }

  public void setTemplate(String template)
  {
    this.template = template;
  }

}
