package com.impetus.process.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserType generated by hbm2java
 */
/**
 * @author amitb.kumar
 */
@Entity
@Table(name = "USER_TYPE")
@GenericGenerator(name = "UserType", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
    @Parameter(name = "segment_value", value = "USER_TYPE"),
    @Parameter(name = "increment_size", value = "10"),
    @Parameter(name = "optimizer", value = "pooled")})
public class UserType implements java.io.Serializable
{

  /**
	 * 
	 */
  private static final long serialVersionUID = 1L;
  /**
	 * 
	 */
  @Id
  @GeneratedValue(generator = "UserType")
  @Column(name = "USER_TYPE_ID")
  private Integer userTypeId;
  /**
	 * 
	 */
  private String internalCode;

  /**
	 * 
	 */
  public UserType()
  {
  }

  /**
   * @param internalCode
   */
  public UserType(String internalCode)
  {
    this.internalCode = internalCode;
  }

  /**
   * @return
   */
  public Integer getUserTypeId()
  {
    return this.userTypeId;
  }

  /**
   * @param userTypeId
   */
  public void setUserTypeId(Integer userTypeId)
  {
    this.userTypeId = userTypeId;
  }

  /**
   * @return
   */
  @Column(name = "INTERNAL_CODE", unique = true, nullable = false)
  public String getInternalCode()
  {
    return this.internalCode;
  }

  /**
   * @param internalCode
   */
  public void setInternalCode(String internalCode)
  {
    this.internalCode = internalCode;
  }

}
