package com.impetus.process.entities;

// Generated Oct 9, 2015 4:20:36 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "Service_Source", uniqueConstraints = @UniqueConstraint(columnNames = "INTERNAL_CODE"))
public class UserRole implements java.io.Serializable {

	private Integer roleId;
	private String internalCode;

	public UserRole() {
	}

	public UserRole(String internalCode) {
		this.internalCode = internalCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "INTERNAL_CODE", unique = true, nullable = false)
	public String getInternalCode() {
		return this.internalCode;
	}

	public void setInternalCode(String internalCode) {
		this.internalCode = internalCode;
	}

}
