package com.impetus.process.entities;

// Generated Oct 9, 2015 4:20:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "USER_TYPE")
@GenericGenerator(name = "UserType", strategy = "org.hibernate.id.enhanced.TableGenerator", parameters = {
		@Parameter(name = "segment_value", value = "USER_TYPE"),
		@Parameter(name = "increment_size", value = "10"),
		@Parameter(name = "optimizer", value = "pooled") })
public class UserType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(generator = "UserType")
	@Column(name = "USER_TYPE_ID")
	private Integer userTypeId;
	private String internalCode;

	public UserType() {
	}

	public UserType(String internalCode) {
		this.internalCode = internalCode;
	}

	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "INTERNAL_CODE", unique = true, nullable = false)
	public String getInternalCode() {
		return this.internalCode;
	}

	public void setInternalCode(String internalCode) {
		this.internalCode = internalCode;
	}

}
