package com.sp.entities;

// Generated Oct 7, 2015 8:00:00 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AggrigatorDetails generated by hbm2java
 */
@Entity
@Table(name = "aggrigator_details", catalog = "Service_Source")
public class AggrigatorDetails implements java.io.Serializable {

	private int aggrigatorId;
	private String firstName;
	private String lastName;
	private String email;
	private int phoneNumber;
	private int zip;
	private String userPassword;

	public AggrigatorDetails() {
	}

	public AggrigatorDetails(int aggrigatorId, String firstName,
			String lastName, String email, int phoneNumber, int zip,
			String userPassword) {
		this.aggrigatorId = aggrigatorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.zip = zip;
		this.userPassword = userPassword;
	}

	@Id
	@Column(name = "AGGRIGATOR_ID", unique = true, nullable = false)
	public int getAggrigatorId() {
		return this.aggrigatorId;
	}

	public void setAggrigatorId(int aggrigatorId) {
		this.aggrigatorId = aggrigatorId;
	}

	@Column(name = "FIRST_NAME", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE_NUMBER", nullable = false)
	public int getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(int phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "ZIP", nullable = false)
	public int getZip() {
		return this.zip;
	}

	public void setZip(int zip) {
		this.zip = zip;
	}

	@Column(name = "USER_PASSWORD", nullable = false)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

}
