package com.sp.entities;

// Generated Oct 9, 2015 4:20:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SpAggregator generated by hbm2java
 */
@Entity
@Table(name = "sp_aggregator", catalog = "Service_Source", uniqueConstraints = @UniqueConstraint(columnNames = "ADDRESS_ID"))
public class SpAggregator implements java.io.Serializable {

	/**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Integer aggregatorId;
	private String businessPhoneNum;
	private String businessPhoneNumExt;
	private String businessEmailAddress;
	private String phoneNum;
	private String phoneNumExt;
	private String webSiteAddress;
	private String logo;
	private int addressId;

	public SpAggregator() {
	}

	public SpAggregator(int addressId) {
		this.addressId = addressId;
	}

	public SpAggregator(String businessPhoneNum, String businessPhoneNumExt,
			String businessEmailAddress, String phoneNum, String phoneNumExt,
			String webSiteAddress, String logo, int addressId) {
		this.businessPhoneNum = businessPhoneNum;
		this.businessPhoneNumExt = businessPhoneNumExt;
		this.businessEmailAddress = businessEmailAddress;
		this.phoneNum = phoneNum;
		this.phoneNumExt = phoneNumExt;
		this.webSiteAddress = webSiteAddress;
		this.logo = logo;
		this.addressId = addressId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AGGREGATOR_ID", unique = true, nullable = false)
	public Integer getAggregatorId() {
		return this.aggregatorId;
	}

	public void setAggregatorId(Integer aggregatorId) {
		this.aggregatorId = aggregatorId;
	}

	@Column(name = "BUSINESS_PHONE_NUM", length = 15)
	public String getBusinessPhoneNum() {
		return this.businessPhoneNum;
	}

	public void setBusinessPhoneNum(String businessPhoneNum) {
		this.businessPhoneNum = businessPhoneNum;
	}

	@Column(name = "BUSINESS_PHONE_NUM_EXT", length = 10)
	public String getBusinessPhoneNumExt() {
		return this.businessPhoneNumExt;
	}

	public void setBusinessPhoneNumExt(String businessPhoneNumExt) {
		this.businessPhoneNumExt = businessPhoneNumExt;
	}

	@Column(name = "BUSINESS_EMAIL_ADDRESS", length = 100)
	public String getBusinessEmailAddress() {
		return this.businessEmailAddress;
	}

	public void setBusinessEmailAddress(String businessEmailAddress) {
		this.businessEmailAddress = businessEmailAddress;
	}

	@Column(name = "PHONE_NUM", length = 15)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	@Column(name = "PHONE_NUM_EXT", length = 10)
	public String getPhoneNumExt() {
		return this.phoneNumExt;
	}

	public void setPhoneNumExt(String phoneNumExt) {
		this.phoneNumExt = phoneNumExt;
	}

	@Column(name = "WEB_SITE_ADDRESS", length = 100)
	public String getWebSiteAddress() {
		return this.webSiteAddress;
	}

	public void setWebSiteAddress(String webSiteAddress) {
		this.webSiteAddress = webSiteAddress;
	}

	@Column(name = "LOGO", length = 500)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "ADDRESS_ID", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

}
