package com.sp.entities;

// Generated Oct 9, 2015 4:20:36 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "user_type", catalog = "Service_Source", uniqueConstraints = @UniqueConstraint(columnNames = "INTERNAL_CODE"))
public class UserType implements java.io.Serializable {

	private Integer userTypeId;
	private String internalCode;

	public UserType() {
	}

	public UserType(String internalCode) {
		this.internalCode = internalCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_TYPE_ID", unique = true, nullable = false)
	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "INTERNAL_CODE", unique = true, nullable = false)
	public String getInternalCode() {
		return this.internalCode;
	}

	public void setInternalCode(String internalCode) {
		this.internalCode = internalCode;
	}

}
